name: Iram Akhtar Designs
favicon: null
layout_spectrum: 0.31503369263373315
typography_spectrum: 0.18888497678563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.47211174271069467
  lightness: 0.1399835569318384
  saturation: 0.7686564014293253
  rhythmicContrast: 0.7302107224240899
purpose: []
